# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ur5_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ur5_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
ur5_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 50000
      d: 100
      i: 10
      i_clamp: 100
    shoulder_lift_joint:
      p: 5000
      d: 30
      i: 10
      i_clamp: 400
    elbow_joint:
      p: 50000
      d: 50
      i: 10
      i_clamp: 100
    wrist_1_joint:
      p: 2000
      d: 20
      i: 1
      i_clamp: 100
    wrist_2_joint:
      p: 1000
      d: 10
      i: 0.01
      i_clamp: 100
    wrist_3_joint:
      p: 1000
      d: 10
      i: 0.01
      i_clamp: 100

