joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

ur5_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]